import words from "@/lib/words";
import Head from "next/head";
import Layout from "@/components/Layout";
import Navbar from "@/components/NavBar";
import { useEffect, useState } from "react";
import GuessContainer from "@/components/GuessContainer";
import Keyboard from "@/components/Keyboard";
import BackgroundBlur from "@/components/BackgroundBlur";
import TutorialModal from "@/components/TutorialModal";
import EndingModal from "@/components/EndingModal";

export const getServerSideProps = () => {
  const randomWord = words[Math.floor(Math.random() * words.length)];
  return {
    props: {
      word: randomWord,
    },
  };
};

export interface PlayerData {
  games: {
    [key: number]: {
      word: string;
      guesses: string[];
    };
  }
}

export default function Home({ word }: { word: string }) {
  const [guess, setGuess] = useState<string>("");
  const [guesses, setGuesses] = useState<string[]>([]);
  const [tutorial, setTutorial] = useState<boolean>(false);
  const [gameOver, setGameOver] = useState<boolean>(false);
  const [showEnding, setShowEnding] = useState<boolean>(false);
  const [playerData, setPlayerData] = useState<PlayerData | null>(null);

  useEffect(() => {
    const playerData = localStorage.getItem("playerData");
    if (playerData) {
      setPlayerData(JSON.parse(playerData));
    } else setPlayerData({ games: {} });
  }, [])

  useEffect(() => {
    console.log("Player data: ", playerData);
    if (playerData) {
      localStorage.setItem("playerData", JSON.stringify(playerData));
    }
  }, [playerData])

  const handleKeyDown = (keyPressed: string) => {
    if (gameOver) return;
    const key = keyPressed.toUpperCase();

    console.log(key);
    if (key.length === 1 && guess.length < word.length) {
      setGuess((prev) => prev + key);
    } else if (key === "BACKSPACE" || key === "BACK") {
      setGuess((prev) => prev.slice(0, -1));
    } else if (
      (key === "ENTER" || key === "RETURN") &&
      guess.length === word.length
    ) {
      setGuess("");
      setGuesses((prev) => [...prev, guess]);
    }
  };

  const PastGuesses = guesses.map((guess, i) => (
    <GuessContainer key={i} chars={guess} correctWord={word} animate={true} />
  ));

  const EmptyGuesses =
    guesses.length < 5
      ? Array.from({ length: 5 - guesses.length - 1 }, (_, i) => (
          <GuessContainer key={i} />
        ))
      : [];

  // Checking if the game should be over
  if (
    !gameOver &&
    (guesses.length === 5 || guesses[guesses.length - 1] === word)
  ) {
    console.log("game over");
    setGameOver(true);
    setShowEnding(true);

    // Saving the game data to local storage
    const playerData = localStorage.getItem("playerData");
    if (playerData) {
      const parsed: PlayerData = JSON.parse(playerData)
      const data = {
        games: {
          ...parsed.games,
          [Date.now()]: {
            word,
            guesses
          }
        }
      }
      setPlayerData(data);
    }
  }

  return (
    <>
      <Head>
        <title>Findle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Navbar
          className="fixed"
          toggleTutorial={() => setTutorial(!tutorial)}
        />
        <main
          className="grid h-screen w-screen bg-neutral-900"
          onKeyDown={(e) => handleKeyDown(e.key)}
          tabIndex={0}
        >
          <div className="grid place-items-center place-self-center rounded-xl bg-neutral-800 p-6 shadow-2xl w-[99vw] sm:w-[60vw] md:w-[50vw] lg:w-[40vw]">
            <h1 className="text-white">{word}</h1>
            <h2 className="text-white">{gameOver ? "true" : "false"}</h2>
            {PastGuesses}
            {guesses.length < 5 && <GuessContainer chars={guess} />}
            {EmptyGuesses}
            <Keyboard
              className="mt-5"
              handleKeyDown={handleKeyDown}
              guesses={guesses}
              correctWord={word}
            />
            {gameOver && (
              <button
                onClick={() => setShowEnding(!showEnding)}
                className={`
                  mt-5 rounded-md
                  border-2 border-black
                bg-blue-700 p-2 text-white
                hover:bg-blue-600
                  active:ring-2 active:bg-blue-700
              `}
              >
                Näytä tulokset
              </button>
            )}
          </div>
          {tutorial && (
            <BackgroundBlur
              toggleBG={() => setTutorial(!tutorial)}
              className="fixed inset-0 z-10"
            >
              <TutorialModal toggleTutorial={() => setTutorial(!tutorial)} />
            </BackgroundBlur>
          )}
          {showEnding && (
            <BackgroundBlur className="fixed inset-0 z-10" toggleBG={() => setShowEnding(!showEnding)}>
              <EndingModal
                playerData={playerData}
                guesses={guesses}
                toggleEnding={() => setShowEnding(!showEnding)}
                correctWord={word}
              />
            </BackgroundBlur>
          )}
        </main>
      </Layout>
    </>
  );
}
